// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8BiEZwUuTcgVuqTGhkGODWCQatP3wH4',
    appId: '1:572865305173:web:dd04c300b3b4024a4dd2dc',
    messagingSenderId: '572865305173',
    projectId: 'vjti-hostel-f8c43',
    authDomain: 'vjti-hostel-f8c43.firebaseapp.com',
    storageBucket: 'vjti-hostel-f8c43.appspot.com',
    measurementId: 'G-KQ1NE6V0X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmudqEKfPuHssS-fqZgb_a1pGbcQeNSds',
    appId: '1:572865305173:android:e9faa9fff9b20a934dd2dc',
    messagingSenderId: '572865305173',
    projectId: 'vjti-hostel-f8c43',
    storageBucket: 'vjti-hostel-f8c43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV76KjqRoChFoIapzcH_AuD2QGOYF8YOU',
    appId: '1:572865305173:ios:e717227166e22b534dd2dc',
    messagingSenderId: '572865305173',
    projectId: 'vjti-hostel-f8c43',
    storageBucket: 'vjti-hostel-f8c43.appspot.com',
    iosBundleId: 'com.example.vjtihostel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV76KjqRoChFoIapzcH_AuD2QGOYF8YOU',
    appId: '1:572865305173:ios:b75d8de69fd4bff64dd2dc',
    messagingSenderId: '572865305173',
    projectId: 'vjti-hostel-f8c43',
    storageBucket: 'vjti-hostel-f8c43.appspot.com',
    iosBundleId: 'com.example.vjtihostel.RunnerTests',
  );
}
